apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-app
          image: padajno/rso-projekt:order-mongo-cloud
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb+srv://admin:rso2022@cluster1.wmakwed.mongodb.net/dbOrder?retryWrites=true&w=majority
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer